### ISSUE TITLE
Actions automatiques et cron/CLI - Résidu dans la DB

### ISSUE THREAD

**Issue by SynCinatti** [DCS-Easyware/gsit#3]
Bonjour, je teste actuellement cette version libérée et ai été confronté à un cron totalement inopérant, bien que configuré correctement (lancement manuel en terminal et/ou exécution forcée d'une tâche CLI fonctionnels).
 Php-errors.log indique : 

_**Fonction Glpi\Marketplace\Controller::croncheckAllUpdates indéfinie (pour les actions automatiques)**_

Après examen de la table glpi_crontasks, il reste cette entrée non désirée... 

<img width="990" alt="Capture d’écran 2021-12-07 à 00 02 46" src="https://user-images.githubusercontent.com/40579356/144936725-f2f66895-5eee-4c9a-b288-da4436dc8b34.png">

**Glpi\Marketplace\Controller, state = 2**

<br/>
<br/>
Une fois cette ligne désactivée (state=0), le cron est de nouveau pleinement fonctionnel, et les actions automatiques de nouveau exécutées.
<br/>
<br/>
Peut-être à supprimer ?

**Comment by ddurieux** [comment]
Oui en effet, surtout que la partie marketplace a été enlevée de cette version 'libérée'.
Comment ça se fait que vous l'avez? vous êtes passé de la 9.5.0 officielle à cette version je pense?

si oui, effectivement, il faut que je gère ce cas ;)

**Comment by SynCinatti** [comment]
Effectivement, j'étais en tests sur la 9.5.1 ;)

**Comment by ddurieux** [comment]
Ok, on va rajouter du code pour gérer ce problème.

**Comment by SynCinatti** [comment]
Merci pour ceux qui feront cette transition :) Je pense de mon côté appliquer cette mise à jour sur mon instance de production, qui est en 9.4.3. Pas de contre-indication?

**Comment by ddurieux** [comment]
Apriori non, le seul bug qu'on doit corriger c'est que l'interface web d'installation / mise à jour a un soucis, donc il faut le faire via la console : php bin/console xxxx

**Comment by SynCinatti** [comment]
Hum, ok, je n'ai jamais fait de mise à jour via la console.. je vais me renseigner. Toutefois, je n'ai pas rencontré de souci via la procédure graphique sur l'instance de test. (Je n'en ai jamais rencontré du tout, d'ailleurs, en 15 ans d'installations et mises à jour diverses et variées.. :-o) Peut-être parce que j'étais déjà en 9.5.x ?

**Comment by SynCinatti** [comment]
Bonsoir, un petit complément rapide, je me suis rendu compte hier que cette entrée dans la db était certainement due au fait que l'action automatique 'CheckAllUpdates' n'était pas nettoyée lors de l'upgrade d'une 'Officielle' vers cette 'libérée'. A toutes fins utiles.. :)

**Comment by ddurieux** [comment]
Oui c'est ça, il y en a peut être d'autre, je vais tout vérifier pour la prochaine release (d'ici quelques jours normalement)

**Comment by felag** [comment]
Bonjour,
juste pour dire qu'on a le même souci ici, en utilisant la console mais sans changer la version de la base de donnée de GLPi 9.5.6 à GSIT 9.5.6.
(Je pense que quand c'est la même version, la commande `php bin/console glpi:database:update` n'a pas vraiment d'action, ce qui me semble normal.)


Est-ce que je peux directement supprimer ça dans la base ou alors mettre à jour en 9.5.7 ou alors "attendre" la prochaine version ?

**Comment by ddurieux** [comment]
Tu ne peux pas en effet quand c'est la même version.

Tu peux (dois?) passer en 9.5.7, surtout qu'il y a des patchs de sécurité ;)
