### ISSUE TITLE
Problem - Sinc FusionInventory x GLPI x replacing tag

### ISSUE THREAD

**Issue by roberto-brasil-sc** [DCS-Easyware/gsit#4]
Translated pt-BR to en-US

I'm a new user on GITHUB let's go to my question - problem.

It has two agents with FusionInventory when synchronized one replaces information from the other in GLPI.

I've already tried reinstalling AGENT, removing TAG completely from GLPI, without success.
I have more other devices with the same AGENT working correctly.

Does anyone have any suggestions?

Awaiting. Thanks. 
Roberto
=================================================
Original

Sou usuário novo no GITHUB vamos a minha dúvida - problema.

Tem dois agentes com FusionInventory quando sincronizados um substitui informação do outro no GLPI.

Já testei reinstalar AGENT, remover TAG totalmente do GLPI, sem sucesso.
Tenho mais outros dispositivos com mesmo AGENT funcionando corretamente.

Alguém tem alguma sugestão?

No aguardo. Obrigado.
Roberto

**Comment by ddurieux** [comment]
in the computer form, in tab import information, see the lastests rules mached. Like this, you can see the rule used to import and identify why have this behavior (perhaps same name, same serial number, other?

**Comment by roberto-brasil-sc** [comment]
@ddurieux , thank you very much for the feedback.

you can adjust FUSIONIVENTORY agent, to one of the criteria to keep record when it is:

>>> different main criteria (mac address x IP address) <<<

Indeed I found the cause with your help, but how to solve?

================================================

COMPUTER 001
 	
[Computer]
Computer Brand Name:	GIGABYTE A320M-S2H
 		
[Motherboard]
Motherboard Model:	GIGABYTE A320M-S2H-CF
Motherboard Chipset:	AMD A320 (Promontory)
Motherboard Slots:	4xPCI Express x1, 1xPCI Express x4, 1xPCI Express x16
PCI Express Version Supported:	v3.0
USB Version Supported:	v3.1
 		
[BIOS]
BIOS Manufacturer:	American Megatrends
BIOS Date:	11/28/2019
BIOS Version:	F50
AMD AGESA Version:	Combo-AM4 1.0.0.4
UEFI BIOS:	Capable
 		
Super-IO/LPC Chip:	ITE IT8686E/CX


System
 	
System Manufacturer:	Gigabyte Technology Co., Ltd.
Product Name:	A320M-S2H
Product Version:	Default string
Product Serial Number:	Default string
UUID:	{03C00218-044D-05F0-6606-FB0700080009}
SKU Number:	Default string
Family:	Default string


Mainboard
 	
Mainboard Manufacturer:	Gigabyte Technology Co., Ltd.
Mainboard Name:	A320M-S2H-CF
Mainboard Version:	x.x
Mainboard Serial Number:	Default string
Asset Tag:	Default string
Location in chassis:	Default string


==================================================================

COMPUTER 002


 	
[Computer]
Computer Brand Name:	GIGABYTE A320M-S2H
 		
[Motherboard]
Motherboard Model:	GIGABYTE A320M-S2H-CF
Motherboard Chipset:	AMD A320 (Promontory)
Motherboard Slots:	4xPCI Express x1, 1xPCI Express x4, 1xPCI Express x16
PCI Express Version Supported:	v3.0
USB Version Supported:	v3.1
 		
[BIOS]
BIOS Manufacturer:	American Megatrends
BIOS Date:	11/28/2019
BIOS Version:	F50
AMD AGESA Version:	Combo-AM4 1.0.0.4
UEFI BIOS:	Capable
 		
Super-IO/LPC Chip:	ITE IT8686E/CX


System
 	
System Manufacturer:	Gigabyte Technology Co., Ltd.
Product Name:	A320M-S2H
Product Version:	Default string
Product Serial Number:	Default string
UUID:	{03C00218-044D-05F0-6606-FF0700080009}
SKU Number:	Default string
Family:	Default string


Mainboard
 	
Mainboard Manufacturer:	Gigabyte Technology Co., Ltd.
Mainboard Name:	A320M-S2H-CF
Mainboard Version:	x.x
Mainboard Serial Number:	Default string
Asset Tag:	Default string
Location in chassis:	Default string


System Enclosure
 	
Manufacturer:	Default string
Case Type:	Desktop
Version:	Default string
Serial Number:	Default string
Asset Tag Number:	Default string
