### ISSUE TITLE
9.5.12 mysqli_sql_exception during GLPI installation on existing clean DB

### ISSUE THREAD

**Issue by eduardomozart** [DCS-Easyware/gsit#41]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.12

### Bug description

During installation process, for database phase, I met a strange SQL error when installing GSIT 9.5.12 on an existing empty DB:

```
Uncaught Exception mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0', `type` int(11) NOT NULL DEFAULT '0' COMMENT 'see' at line 4 in /public_html/glpi/inc/dbmysql.class.php at line 302
```

### Relevant log output

```shell
[2024-04-15 13:20:58] glpiphplog.WARNING: Test logger  
[2024-04-15 13:21:50] glpiphplog.CRITICAL:   *** Uncaught Exception mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '&#039;0&#039;,
  `type` int(11) NOT NULL DEFAULT &#039;0&#039; COMMENT &#039;see' at line 4 in /home/robertinho/public_html/glpi/inc/dbmysql.class.php at line 302
  Backtrace :
  inc/dbmysql.class.php:302                          mysqli->query()
  inc/dbmysql.class.php:831                          DBmysql->query()
  inc/toolbox.class.php:2566                         DBmysql->runFile()
  install/install.php:405                            Toolbox::createSchema()
  install/install.php:672                            step4()
```

### Page URL

https://glpi.example.com/install/install.php

### Steps To reproduce

Following https://glpi-install.readthedocs.io/en/latest/install/wizard.html ...
After step "Database choice" using an existing database.

### Your GLPI setup information

```markdown
Database server
Server: Localhost via UNIX socket
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.30-cll-lve - MySQL Community Server - (GPL)
Protocol version: 10
User: robertinho@localhost
Server charset: cp1252 West European (latin1)

Web server
cpsrvd 11.110.0.24
Database client version: libmysql - mysqlnd 8.1.27
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.1.27
```

### Anything else?

This seems similar to https://github.com/glpi-project/glpi/issues/10793 and fixed on GLPI nightly builds, but I was unable to trackdown the fix.
When executing the contents of ``install/mysql/glpi-empty.sql`` directly from phpMyAdmin, the query executed as expected.

**Comment by eduardomozart** [comment]
I was able to fix it applying the fix at https://github.com/DCS-Easyware/gsit/blob/gsit9.5/bugfixes%2Bphp81/inc/dbmysql.class.php#L834

**Comment by ddurieux** [comment]
I had this problem one time, but unable to reproduce after, this behavior is very strange :/
