### ISSUE TITLE
please remove webserver (apache, nginx...) write permission on folder : /var/www/html/glpi/config`

### ISSUE THREAD

**Issue by Riesuu** [DCS-Easyware/gsit#5]
Bonjour,
je viens de mettre à jour GSIT 9.56 vers la GSIT 9.5.7, tout s'est très bien déroulé, par contre j'ai le message suivant qui apparait::

`For security reasons, please remove webserver (apache, nginx...) write permission on folder : /var/www/html/glpi/config`

J'ai désactivé tous les plugins et le message est toujours présent.

Je créé un ticket ici car une personne l'a déjà fait sur l'officiel: https://github.com/glpi-project/glpi/issues/10568

merci :)

**Comment by ddurieux** [comment]
C'est une sécurité suplémentaire que j'ai ajouté dans le fork.
Le dossier glpi/config ne doit pas avoir les droits d'écriture par Apache.

Apparement t'es sous Linux, donc un `chown -R xxx /var/www/html/glpi/config` ou xxx peut être le user root

**Comment by Riesuu** [comment]
Effectivement ! Merci je n'avais jamais vu ça..j'ai donc passé en 555 le /config
