### ISSUE TITLE
Permisions sur le dossier config: erreur en console ou bloc jaune sur l'interface web

### ISSUE THREAD

**Issue by felag** [DCS-Easyware/gsit#6]
Avec GSIT 9.5.7.

Pour utiliser la console (mise à jour, statut…), l'utilisateur apache/nginx/php doit avoir les droits d'écriture sur `/config` sinon une erreur s'affiche:
```
supportpreprod@probphp7preprod:~/www$ php7.3 bin/console   glpi:system:status
PHP Warning:  mkdir(): Permission denied in /home/supportpreprod/www/inc/toolbox.class.php on line 1483
Certains prérequis système sont manquants. Lancez "php bin/console glpi:system:check_requirements" pour plus de détails.
```
Effectivement, la vérification des pré-requis affiche une erreur:
![Capture d’écran de 2022-02-17 15-40-27](https://user-images.githubusercontent.com/30040524/154504822-c0c614cd-35d7-40fa-9cb0-1bc039f4dba3.png)

Si je modifie les permissions sur le dossier avec la commande suivante: `chown www-data: config/` (où `www-data` est l'utilisateur apache/nginx/php), alors l'erreur disparaît.

**MAIS** un bloc jaune apparaît dans l'interface web (avec le profil `super-admin`):
![image](https://user-images.githubusercontent.com/30040524/154505882-ab920695-78ce-4445-a3fc-168b40a18c30.png)

Est-ce qu'il serait possible de ne pas avoir d'erreur (ni en pré-requis ni sur l'interface web) ?

**Comment by Riesuu** [comment]
Bonjour,
un chmod -R 555 sur le /config et cela a résolu(sécurisé) le répertoire.  https://github.com/DCS-Easyware/gsit/issues/5
