### ISSUE TITLE
Impossible d'écire sur le dossier config

### ISSUE THREAD

**Issue by Riesuu** [DCS-Easyware/gsit#8]
Bonjour,
sur une nouvelle et fresh install, lors de l'étape des pré-requis pour l'installation. Il m'est impossible de continuer car GSIT me demande de donner les droits en écritures sur le dossier config/.

Mon dossier config a été testé en Chmod 55 -> NOK ou en CHMOD 755->NOK

Par contre, en passant via l'installation en cli, tout a fonctionné correctement.

GSIT 9.5.7

Debian 11
Apache 2.4
PHP 8

**Comment by ddurieux** [comment]
en web, il faut mettre les droits apache/www sur le dossier config, puis les enlever juste après.
